# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 07262cfe13df691188fe09ebc0ab50df1904d057f0bce3f82f926bd18ae84b62a6ea56baf15a82b0beaf4954447e3c24c578f85dfbd58ced296fb5202e478c34

test:
  secret_key_base: 0215daefbc20d4a62cb01d3aa31eff34a102f6ff6dde452c35b28576f68ee548920a671217116d39ff9d69436001831c7642a807711eac9d315e2730ea0d38a8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
